name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vim_version:
        - 'v8.2.0000'
        - 'v8.1.0000'
        - 'v8.0.0000'
        - 'v7.4'
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Checkout vim-themis
      uses: actions/checkout@master
      with:
        repository: thinca/vim-themis
        path: vim-themis

    - name: Setup Vim
      uses: thinca/action-setup-vim@v1
      with:
        vim_version: ${{ matrix.vim_version }}

    - name: echo Vim version
      run: vim --version

    - name: Test
      env:
        THEMIS_VIM: ${{ steps.vim.outputs.executable }}
      run: ./vim-themis/bin/themis --reporter spec
